### ISSUE TITLE
Use a new user created via personatestuser for all tests

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/bidpom#96]
Some of our tests for bidpom are currently failing [1] because the existing email address that we had been using, which is webqabrowserid@aol.com, seems to have become unknown to Persona. I tried to fix this manually by requesting a new Persona account via the login workflow while manually running the test, but there is a problem that the confirmation email is never sent, so we cannot finish the registration process.

I recall that this happened at least once before, and required help from the Identity team. I'm thinking that we could avoid this whole issue by simply using personatestuser for all of these tests. As these are tests for bidpom, and not Persona itself, I see no reason why we should need to use a "real" existing user for the tests, as opposed to a temporary existing user created via personatestuser.

Therefore I suggest we change all of the tests to use personatestuser, rather than webqabrowserid@aol.com, which will fix the tests for now and will also avoid this issue coming back in the future.

Do people agree with this approach? @davehunt what do you think?

[1] https://webqa-ci.mozilla.com/job/bidpom.stage.saucelabs/403/HTML_Report/

**Comment by m8ttyB** [comment]
I'm in transit today, so can't do much until I land in SF. I reached out to jrgm yesterday to help solve this. Hopefully this is still on his radar. I'll check status again once I'm in Moz SF.Cheers and big thanks for helping solve this.Mattmozilla/bidpom wrote:Some of our tests for bidpom are currently failing [1] because the existing email address that we had been using, which is webqabrowserid@aol.com, seems to have become unknown to Persona. I tried to fix this manually by requesting a new Persona account via the login workflow while manually running the test, but there is a problem that the confirmation email is never sent, so we cannot finish the registration process.

I recall that this happened at least once before, and required help from the Identity team. I'm thinking that we could avoid this whole issue by simply using personatestuser for all of these tests. As these are tests for bidpom, and not Persona itself, I see no reason why we should need to use a "real" existing user for the tests, as opposed to a temporary existing user created via personatestuser.

Therefore I suggest we change all of the tests to use personatestuser, rather than webqabrowserid@aol.com, which will fix the tests for now and will also avoid this issue coming back in the future.

Do people agree with this approach? @davehunt what do you think?

[1] https://webqa-ci.mozilla.com/job/bidpom.stage.saucelabs/403/HTML_Report/

—Reply to this email directly or view it on GitHub.

  
    
    
  
  
Sent Using Firefox OS

**Comment by bobsilverberg** [comment]
Thanks @m8ttyB. It probably makes sense to follow up with @jrgm to see if we can get this fixed in the sort term, as was done before, as this is not an insignificant change to this test suite, so while I think it would be a big improvement, I'm not sure how we should prioritize it amongst the other work we have to do. Fixing the issue with  `webqabrowserid@aol.com` would at least unblock the tests.

**Comment by jrgm** [comment]
So, using personatestuser.org to create temporary test accounts is a good practice. 

I'm not sure exactly why webqabrowserid@aol.com is missing, but I expect in @relud's work to migrate stage persona to a different IAM, he chose not to migrate the existing accounts. @relud, yes?

As for not getting a signup email for webqabrowserid@aol.com, I can't say why. I know that outbound emails from login.anosrep.org are happening as I can get one. Hate to ask the obvious, but did you check the spam folder for webqabrowserid@aol.com? If you're sure it's not there, @relud can see if there is a bounce mail logged (still on socketlabs, right?).

**Comment by relud** [comment]
`in @relud's work to migrate stage persona to a different IAM, he chose not to migrate the existing accounts.` that is correct

`As for not getting a signup email` The migration probably broke DKIM as well, I'm working on fixing this.

In general, it's also a much better idea to point your test at persona.org instead of anosrep.org, because anosrep.org is persona's staging environment. The environment is prone to breakage, because it's stage, so it needs to be allowed to break, and it's where any changes to persona are tested (such as config changes).

**Comment by relud** [comment]
`The migration probably broke DKIM as well` i double-checked, and nothing changed regarding email settings for anosrep.org, so i'm not sure what could be going wrong here. checking socketlabs for more info.

**Comment by jrgm** [comment]
> In general, it's also a much better idea to point your test at persona.org instead of anosrep.org, because anosrep.org is persona's staging environment.

That would be a change from 3+ years of running these tests. Yeah, stuff can bounce on occasion and that's fine.

**Comment by jrgm** [comment]
Although, I suppose, since we don't do new code in stage, whether these tests might be better to move to login.persona.org (although a testing-new-code-in-production alarm just went off somewhere).

**Comment by bobsilverberg** [comment]
Thanks @jrgm and @relud. We could move the tests to login.persona.org if that's desired, but I don't see a consensus above. As for using personatestuser against http://beta.123done.org, which is the site we're using for testing now, that doesn't work as I assume it's the wrong Persona environment (which is exactly what you two were discussing above). If we want to keep testing against http://beta.123done.org, is there an instance of personatestuser that we can use, and if so, what's the address?

**Comment by davehunt** [comment]
I agree that we should be using a temporary test account wherever possible. I suspect that personatestuser wasn't available when we first wrote these tests.

I have restored coverage in the meantime by logging into our webqabrowserid@aol.com and completing the sign in. I'm not sure why this wasn't working for @bobsilverberg.

**Comment by jrgm** [comment]
So personatestuser knows about our staging environment too. Load the home page and it's even documented. Just call http://personatestuser.org/email/stage to get an account for use on beta.123done.org.

**Comment by jrgm** [comment]
> I suspect that personatestuser wasn't available when we first wrote these tests.

Yeah, definitely.

**Comment by bobsilverberg** [comment]
Thanks @jrgm, using that staging url worked! And, for the record, I don't see anything on http://personatestuser.org/ that tells me how to get a staging address. What am I missing?

**Comment by jrgm** [comment]
Ah, right. Documented only in the sense of a REST call `GET /email/:env` and me inflating that to be "documentation" ;-).

**Comment by bobsilverberg** [comment]
Maybe it should be actually documented?

Also, FTR, I am now actively working on this.

**Comment by davehunt** [comment]
I've addressed this in #98

**Comment by davehunt** [comment]
Fixed in https://github.com/mozilla/bidpom/commit/348811d04fc0764be16da3f06d90e920f67d4658
